[graph]
all-features = true

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
]

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
]
confidence-threshold = 1.0
