[graph]
all-features = true

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"

# The instant crate is unmaintained, but we need to depend on
# it to avoid bumping our MSRV. This should be fixed once our
# MSRV is at least 1.77.
[[advisories.ignore]]
id = "RUSTSEC-2024-0384"

[licenses]
allow = [
    "CC0-1.0", # unencumbered
    "ISC", # notice
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
    "BSD-3-Clause", # notice
]
confidence-threshold = 1.0
