[workspace]
# disable the changelog for all packages, will only enable for shpool
changelog_update = false
# disable creating release by default, will only enable for shpool
git_release_enable = false
git_release_type = "auto"

[changelog]
header = ""
body = """
{{ package }} ({{ version | trim_start_matches(pat="v") }}) unstable; urgency=low
{% for group, commits in commits | group_by(attribute="group") %}
  {{ group | upper_first }}
{% for commit in commits -%}
{%- if commit.scope %}
  * *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{%- else %}
  * {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{%- endif %}
{%- endfor %}
{% endfor %}
 -- Shpool Authors <shpool-eng@google.com>  {{ now() | date(format="%a, %d %b %Y %T %z") }}
"""
trim = false

[[package]]
name = "shpool"
changelog_update = true
changelog_path = "./debian/changelog"
# Also include changes in files in libshpool
changelog_include = ["libshpool"]
# Use bare vx.y.z version tag for shpool, other packages will use the default
# packagename-vx.y.z tag
git_tag_name = "v{{ version }}"
# GitHub release will only be created for the overall shpool binary
git_release_enable = true
git_release_name = "v{{ version }}"

[[package]]
name = "libshpool"
# libshpool doesn't get its own tag since it's always the same version as shpool
git_tag_enable = false

[[package]]
name = "shpool-protocol"
changelog_update = true
changelog_path = "./shpool-protocol/CHANGELOG"
